name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:sensebox_mcu_esp32s2
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          sketch-paths: |
            - ./blink
          libraries: |
            - name: SenseBoxBLE
            - name: SDConfig
            - name: SD
            - name: "Adafruit HDC1000 Library"
            - name: sps30
            - name: Adafruit_MPU6050
            - name: NewPing
            - name: display
            - name: vl53l8cx_class
            - name: Adafruit_GFX
            - name: Adafruit_SSD1306
            - name: qrcode
            - name: Adafruit_MAX1704X
